### ISSUE TITLE
Update Only one Student at a time

### ISSUE THREAD

**Issue by sushil-0** [celerispay/crud-application-arpan#13]
https://github.com/celerispay/crud-application-arpan/blob/c595ed19c9be4d58203fc46c05a4bde7567e8a08/src/main/java/com/crudapplication/service/StudentService.java#L44

**Comment by arpanagnihotri** [comment]
#updating only one student at a time

@Transactional
	public void updateStudent(@Valid Student student, int id) {
		log.info("updating students with given id:{}", id);
		Optional<Student> optionalStudent = repository.findById(id);

		if (optionalStudent.isPresent()) {
			Student existingStudent = optionalStudent.get();

			existingStudent.setName(student.getName());
			existingStudent.setMarks(student.getMarks());
			repository.save(existingStudent);
		} else {
			throw new EntityNotFoundException("Student with ID " + id + " not found");
		}

	}
